name: Build and Deploy

on:
  push:
    branches:
      - source

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node 10
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Lint
        run: npm run lint
        env:
          CI: true

      - name: Build
        run: |
          npm run build
          touch public/.nojekyll
        env:
          CI: true

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.5.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main
          FOLDER: public
